#ifndef TOKENS_H
#define TOKENS_H

typedef enum
{
    OP_PLUS = 1, OP_MINUS, OP_MULT, OP_DIV, 
    OP_OPEN_P, OP_CLOSE_P, INTEGER, IDENTIFIER,
    COMMENT, OP_EQUAL, POINTER, OP_OPEN_CURLY, 
    OP_CLOSE_CURLY, OP_OPEN_SQU, OP_CLOSE_SQU,
    OP_COMMA, OP_DOT, OP_OPEN_ANGLE, OP_CLOSE_ANGLE,
    OP_SEMICOLON

}
typeOfToken;

#endif
