name: C CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: install flex development files
      run: |
      	sudo apt-get update
      	sudo apt-get install -y libfl-dev

    - uses: actions/checkout@v4

    - name: build
      run: make YACCFLAGS=""
